### ISSUE TITLE
Windows 10 Enterprise 64-bit

### ISSUE THREAD

**Issue by igorpereirabr1** [fabiogjardim/bigdata_docker#2]
Olá... Infelizmente meu SO: Windows 10 Enterprise 64-bit não tem suporte para virtualizacão:
![image](https://user-images.githubusercontent.com/29541571/78897176-25e1a400-7a48-11ea-8c5d-0d2fd1fa219b.png)

![image](https://user-images.githubusercontent.com/29541571/78897256-4578cc80-7a48-11ea-9690-75f4579a2367.png)

Atualmente utilizo o Docker Desktop Windows, dependente do Hyper-V, que quando ativo é incompatível com o VirtualBox...

Infelizmente por se tratar de um computador corporativo, não posso alterar a BIOS para ativar a virtualizacão.

Com base nesse cenário, alguma sugestão? Infelizmente não conheco muito de docker, mas acho que dever ter alguma alternativa.

**Comment by fabiogjardim** [comment]
@igorpereirabr1 creio que rode com o Docker Desktop Windows sim, tente rodar o docker compose no powershell.

**Comment by igorpereirabr1** [comment]
Fucnionou! entretanto tive que alterar os volumes no docker-compose.yml.. estava como: 
- /**d**/docker/bigdata_docker/ e alterei para - /**c**/docker/bigdata_docker/

O metabase também não funcionou, aí busquei a imagem oficial **metabase/metabase**

Obrigado pelo suporte!
