### ISSUE TITLE
Dúvida sobre docker

### ISSUE THREAD

**Issue by adornogomes** [fabiogjardim/bigdata_docker#5]
Olá Fábio,

Por favor, de acordo com a imagem do ecossistema, cada um dos itens será colocado em um container específico? Por exemplo, o MongoDB e o Mongo Express ficariam em containers separados ou no mesmo container?

Muito obrigado,

Daniel Adorno Gomes

**Comment by fabiogjardim** [comment]
Olá @adornogomes , cada um fica em um container separado.
Somente o sqoop e o namenode esta no mesmo container.
