### ISSUE TITLE
ingest data / demo example

### ISSUE THREAD

**Issue by ghost** [fabiogjardim/bigdata_docker#6]
Hi,

Hope you are all well !

Is it possible to provide an example of ingesting a csv file into this stack ?

Thanks in advance for any insights or inputs on that issue.

Cheers,
X

**Comment by fabiogjardim** [comment]
the most easily mode to upload csv file in HDFS is with Apache Hue, like image below 
![image](https://user-images.githubusercontent.com/20249737/83684845-1604bd00-a5be-11ea-9ffc-4468944d1757.png)

you can also use docker cp to copy csv to datanode container or access datanode container and create local csv file 

docker exec -it datanode bash

**Comment by ghost** [comment]
Thanks for the reply !

Is it working for big dump like 5/10Gb ?

Also, Can I add data to hdfs with kafka ?

I do not get if all the containers are connected or independent ?

**Comment by fabiogjardim** [comment]
The containers are connected.
To put message with Kafka to HDFS you can work with Apache Nifi.

![image](https://user-images.githubusercontent.com/20249737/83924156-3ff2e680-a75a-11ea-818d-8ffe4c0b3f7f.png)
